project_id = "bsvwkjxqvcdomsrtbwre"

[functions.analyze-car]
verify_jwt = true

[functions.generate-ai-report]
verify_jwt = true

[functions.increment-impression]
verify_jwt = false

[functions.send-reset-email]
verify_jwt = false

[functions.request-password-reset]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false
